### ISSUE TITLE
Copy fail: Invalid protocol:FIle

### ISSUE THREAD

**Issue by dtorg** [BoolBySigma/FetchBuildArtifact#2] opened 2017-04-10 15:43 UTC
I get an error when the copy is attempted. It creates the destination folder but fails to copy the artifact.
---------------
``Querying project 'Instrument Control' for completed successful builds of build definition '669'

build:

{"_links":{"self":{"href":"http://tfs:8080/tfs/DefaultCollection/dad31c62-fbe8-4d21-851e-bd512969b1f4/_apis/build/Builds/39950"},"web":{"href":"http://tfs:8080/tfs/_permalink/_build/index?collectionId=4b019454-626e-4582-b569-ee8f8bbefa4d&projectId=dad31c62-fbe8-4d21-851e-bd512969b1f4&buildId=39950"},"details":{"href":"http://tfs:8080/tfs/DefaultCollection/dad31c62-fbe8-4d21-851e-bd512969b1f4/_apis/build/Builds/39950/Details?api-version=1.0"}},"id":39950,"buildNumber":"InstrumentControlSDK_Aries10_Market1.Rel_2.1.942.0_B.1","status":"completed","result":"succeeded","queueTime":"2015-04-04T06:00:00.72Z","startTime":"2015-04-04T06:00:04.75Z","finishTime":"2015-04-04T06:17:24.067Z","url":"http://tfs:8080/tfs/DefaultCollection/dad31c62-fbe8-4d21-851e-bd512969b1f4/_apis/build/Builds/39950","definition":{"type":"xaml","createdDate":"2014-11-03T17:42:17.55Z","id":669,"name":"InstrumentControlSDK_Aries10_Market1.Rel","url":"http://tfs:8080/tfs/DefaultCollection/dad31c62-fbe8-4d21-851e-bd512969b1f4/_apis/build...

buildId=39950
Found build '39950'
Querying build artifact 'drop'
Found build artifact 'drop'
Downloading build artifact 'drop' to C:\BuildAgent2017\_work\1\s\Prerequisites\drop.zip

task result: Failed

Invalid protocol: file:

Processed: ##vso[task.issue type=error;]Invalid protocol: file:

Processed: ##vso[task.complete result=Failed;]Invalid protocol: file:``

**Comment by ghost** [comment] 2017-04-12 18:40
Does the folder Prerequisites exist?

Currently the folder structure must exist. I patch for this is planned.

**Comment by dtorg** [comment] 2017-04-12 19:24
It appears Fetch Artifact is creating the Prerequisites folder in the correct location. It fails to create the drop.zip file at that location.

Thanks,
David R. Torgerson | Director Software Applications | Direct.: (512) 381-3233 | dtorg@luminexcorp.com<mailto:dtorg@luminexcorp.com>
Luminex Corporation | 12212 Technology Blvd, Austin, TX  78727 | www.luminexcorp.com<http://www.luminexcorp.com/>

**Comment by ghost** [comment] 2017-04-13 09:04
You could try downloading drop.zip to an existing folder and see if that works for you. I will try to reproduce the error.

**Comment by ghost** [comment] 2017-04-13 09:12
I have been unable to reproduce the error.

Could you please run the build with variable system.debug set to true and post the log?

**Comment by dtorg** [comment] 2017-04-13 14:00
I’ve attached the logs for the run with debug on.

You mentioned “try downloading drop.zip”. Does this mean drop.zip must already exist for the artifact? I had assumed this utility zipped the files at the source location and copied the files. Is this not the case? Could there be a credentials problem at the source folder?

Thanks,
David R. Torgerson | Director Software Applications | Direct.: (512) 381-3233 | dtorg@luminexcorp.com<mailto:dtorg@luminexcorp.com>
Luminex Corporation | 12212 Technology Blvd, Austin, TX  78727 | www.luminexcorp.com<http://www.luminexcorp.com/>

**Comment by ghost** [comment] 2017-04-13 14:28
Im not seeing the attached log. Could you please upload it using the github page?

The artifact is automatically zipped. I thought perhaps the target folder had to exist but I have ruled that out?

Are you using Server or File Share to store your artifact? The task is currently only tested for Server.

**Comment by dtorg** [comment] 2017-04-13 14:54
[logs_64547.zip](https://github.com/BoolBySigma/FetchBuildArtifact/files/920020/logs_64547.zip)

The artifact is on a file share. I am dropping the artifact to the build source location.

**Comment by ghost** [comment] 2017-04-13 16:25
This is a duplicate of https://github.com/BoolBySigma/FetchBuildArtifact/issues/1

I will be looking into this

**Comment by ghost** [comment] 2017-04-13 22:10
Published an update that supports both server and file share

**Closed as completed by ghost** 2017-04-13 22:10 UTC
Labels: duplicate
